# Pipeline for Model Scoring

pool: 
   vmImage: ubuntu-latest
stages:
  - stage: ContinuousIntegration
    jobs:
    - job: ImageBuild
      steps:
        - task: DockerInstaller@0
          displayName: Step 0b - Installing the Docker (Pre-requisite)
          inputs:
            dockerVersion: '17.09.0-ce'
        - task: ECRPullImage@1
          displayName: Step 0c - Pulling the base image from ECR
          inputs:
            awsCredentials: 'aws-raphael-dev'
            regionName: 'ap-southeast-1'
            repository: 'ptawsg-ecr-rph-ds-models'
            imageSource: 'imagetag'
            imageTag: 'rph-base-rdocker'
            logResponse: true
        - task: CmdLine@2
          displayName: Step 1a - Re-tagging the base image container
          inputs:
            script: |
              docker tag 900051432098.dkr.ecr.ap-southeast-1.amazonaws.com/ptawsg-ecr-rph-ds-models:rph-base-rdocker rph-base-rdocker:dev
        - task: DownloadSecureFile@1
          name: caCertificate
          displayName: Step 1b - Download config_FE.yml from Secrets
          inputs:
            secureFile: 'config_FE.yml'
        - task: CmdLine@2
          displayName: Step 1c - Moving config_FE.yml to folder
          inputs:
            script: |
              echo Downloading the config yml...
              cwd=$(pwd)"/sm-r/docker_config"
              echo $cwd
              mkdir $cwd
              cp $(caCertificate.secureFilePath) $cwd/config.yml
              echo $cwd
        - task: CmdLine@2
          displayName: Step 2 - Building Docker image (development environment) - Monthly Model training (Sagemaker sample)
          inputs:
            script: docker build --force-rm -t rph-demo-sm:sm -f sm-r/dockerfiles/sampleR.Dockerfile .
        - task: ECRPushImage@1
          displayName: Step 3 - Pushing the (Sagemaker sample) to development ECR 
          inputs:
            awsCredentials: 'aws-raphael-dev'
            regionName: 'ap-southeast-1'
            imageSource: 'imagename'
            sourceImageName: 'rph-demo-sm'
            sourceImageTag: 'sm'
            repositoryName: 'ptawsg-ecr-rph-ds-models'
            pushTag: 'rph-demo-sm'
        
